production:
  phpSettings:
    display_startup_errors: 0
    display_errors: 0
    date:
      timezone: UTC
  includePaths:
    library: APPLICATION_PATH/../library
  autoloaderNamespaces:
    - Mn_
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  pluginpaths:
    Mn_Application_Resource: Mn/Application/Resource
  appnamespace: App
  resources:
    frontController:
      controllerDirectory: APPLICATION_PATH/controllers
      moduleDirectory: APPLICATION_PATH/modules
      actionhelperpaths:
        Mn_Controller_Action_Helper_: APPLICATION_PATH/../library/Mn/Controller/Action/Helper
      params:
        displayExceptions: 0
    layout:
      layoutPath: APPLICATION_PATH/layouts/scripts/
    locale:
      default: en_US
#      force: true
    view:
      encoding: UTF-8
      basePath: APPLICATION_PATH/views/
      doctype: XHTML1_TRANSITIONAL
      contentType: text/html; charset=UTF-8
      charset: UTF-8
      helperPath:
        Mn_View_Helper_: APPLICATION_PATH/../library/Mn/View/Helper
    translate:
      adapter: gettext
      content: APPLICATION_PATH/../data/locales
      scan: directory
      options:
        logUntranslated: true
    cachemanager:
      memcached:
        frontend:
          name: Core
          options:
            automatic_serialization: On
        backend:
          name: Libmemcached
          options:
            servers:
              one:
                host: localhost
                port: 11211
                persistent: On
     session:
       name: mn_website_session_id
       gc_maxlifetime: 7200
       use_only_cookies: true
       remember_me_seconds: 864000
    mnFacebook:
      appName: mn-skeleton
      appId: 172116222801586
      secret: 1a9d4b551d7feb847a24d06d45115024
      cookie: true
    mnSdk:
      uri: api.sandbox.mambanation.com
      username: skeleton
      password: m1m36
    mnlog:
      stream:
        writerName: Stream
        writerParams:
          stream: APPLICATION_PATH/../data/logs/application.log
        filterName: Priority
        filterParams:
          priority: 4
      mail:
        writerName: Mail
        writerParams:
          charset: UTF-8
          from: sender@website.com
          to: alert-receiver@website.com
          subjectPrependText: '[ALERT WEBSITE] - Critical error occured - Errors from script"
        filterName: Priority
        filterParams:
          priority: 2
          
testing:
  _extends: production
  phpSettings:
    display_startup_errors: 1
    display_errors: 1
    
development:
  _extends: production
  display_startup_errors: 1
  display_errors: 1
  resources:
    frontController:
      params:
        displayExceptions: 1
    mnlog:
      stream:
        filterParams:
          priority: 7
  turbine:
    debug_level: 2
    minify_css: false
